package com.passgo.app.core.model

enum class CategoryIconIdentifier {
    GOOGLE,
    EMAIL,
    SOCIAL_MEDIA,
    BANKING,
    SHOPPING,
    WORK,
    ENTERTAINMENT,
    GAMING,
    WIFI,
    SOFTWARE_LICENSE,
    SECURE_NOTE,
    CREDIT_CARD,
    DEBIT_CARD,
    BANK_ACCOUNT,
    PAYPAL,
    WISE,
    STRIPE,
    PASSPORT,
    NATIONAL_ID,
    DRIVER_LICENSE,
    RESIDENCE_PERMIT,
    HEALTH_INSURANCE,
    SOCIAL_SECURITY,
    TAX_ID,
    STUDENT_ID,
    OTHER
}
